server: 
  port: 9010
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.204.215.187:3306/tensquare_gathering?useSSL=false&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
  redis:
    host: 129.204.215.187
  rabbitmq:
    host: 129.204.215.187
    username: guest
    password: guest
