server: 
  port: 9003
spring:
  application:
    name:  tensquare_qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
logging:
  root:
    level: DEBUG

