server: 
  port: 9006
spring:
  application:
    name: tensquare_spit
  data:
    mongodb:
      host: 129.204.215.187
      username: tensquare_mongo
      database: spit
logging:
  root:
    level: DEBUG

