server: 
  port: 9004
spring:
  application:
    name:  tensquare_article
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://129.204.215.187:3306/tensquare_gathering?useSSL=false&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    show-sql: true
    database: mysql
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
logging:
  root:
    level: DEBUG

